<!DOCTYPE html>   
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!--Link Bootstrap-->
    <link rel="stylesheet" href="CSS/bootstrap/css/bootstrap.min.css"> 
</head>
<body>
<div class="container" style="margin-top: 80px;">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Login Section
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        <div class="form-group">
                            <label for="userName">Enter your username</label>
                            <input type="text" name="userName" id="userName" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="userPass">Enter your password</label>
                            <input type="password" name="userPass" id="userPass" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn btn-outline-warning">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <form action=" " method="post"> </form>
        </div>


    </div>
</div>
</body>
</html>
